### ISSUE TITLE
模式设置问题

### ISSUE THREAD

**Issue by zack66** [CareyWang/sub-web#1]
![image](https://user-images.githubusercontent.com/16634459/74173078-67ceb380-4c6c-11ea-8a5a-fef1a3172e80.png)

您好，我想问一下修改哪个文件可以让他默认选择基础模式

**Comment by CareyWang** [comment]
@zack66 src/views/Subconverter.vue，line 150  advanced改为1

**Comment by zack66** [comment]
谢谢！
