### ISSUE TITLE
请问 BackendVersion 是根据哪里获取的？

### ISSUE THREAD

**Issue by exlulu** [CareyWang/sub-web#104]
貌似一直只会显示 v0.7.1-2f78eaf，不是我机器上正在运行的版本，也不是后端github上最新的版本，请问 BackendVersion 是根据哪里获取的？能否指定获取我机器上正在运行的本？

**Comment by RodmanWang** [comment]
同求

**Comment by CareyWang** [comment]
默认请求配置的后端 /version 的结果

**Comment by exlulu** [comment]
> 默认请求配置的后端 /version 的结果

已解决，谢谢

**Comment by Dawneng** [comment]
> > 默认请求配置的后端 /version 的结果
> 
> 已解决，谢谢

请问一下 如何解决的？

**Comment by exlulu** [comment]
> > > 默认请求配置的后端 /version 的结果
> > 
> > 
> > 已解决，谢谢
> 
> 请问一下 如何解决的？

修改[.env](https://github.com/CareyWang/sub-web/blob/master/.env)
