### ISSUE TITLE
项目根目录

### ISSUE THREAD

**Issue by Amour-TiAmo** [CareyWang/sub-web#112]
握草了老哥，你这目录非得是跟下吗？我想放二级菜单，打开就显示个白板，我都不知道改了多少次指向目录位置[
![image](https://user-images.githubusercontent.com/83706001/170814571-4004228d-b379-4dca-a5c4-710acadbd8e5.png)
](url)
[
![image](https://user-images.githubusercontent.com/83706001/170814588-aaf6d066-a1b3-4e37-8e66-5e0fcbfa041e.png)
](url)

**Comment by CareyWang** [comment]
https://github.com/CareyWang/sub-web/issues/94
