### ISSUE TITLE
转换成v2ray订阅好像出bug了，是无效链接

### ISSUE THREAD

**Issue by lisonglin980** [CareyWang/sub-web#118]
之前转换出来的订阅链接一直都是正常的，然后大概半个月前订阅链接订阅不上了，我尝试了转基础模式和进阶模式的V2ray客户端的链接，打开都是如图片所示的格式，和以前转出来的不一样。（仅V2ray有问题，clash正常）
![image](https://user-images.githubusercontent.com/68982838/185376201-1e4fcbf3-bea5-46ad-bd54-4364dd7a9d2b.png)

**Comment by WenYe2021** [comment]
同样遇到这个问题，转换clash正常，转v2ray到客户端里就显示无效订阅，然后把链接在浏览器打开得到编码复制后再在客户端里粘贴又可以载入线路
