### ISSUE TITLE
基于Fork的版本搞的单文件版

### ISSUE THREAD

**Issue by heartnn** [CareyWang/sub-web#13]
个人认为携带更方便，能不能以后直接做个发行版本。

这个是我根据Fork的版本做的：
https://github.com/heartnn/sub-web/releases/download/1.1.pre/sub-web.html

css,js和用到的字体都放进去了。

**Comment by CareyWang** [comment]
项目为单页应用，为了 url 美观目前路由采用 history 模式，需要服务器提供回退至index.html的支持，暂时不考虑修改路由模式或打包输出路径并提供静态化文件，需要请自行打包或采用 CDN 引入依赖在单 html 文件中实现。

使用 yarn 管理依赖方便后期新增功能，配合CI实现推送自动部署，推荐配合 netlify 或 now.sh 此类服务托管使用。

**Comment by heartnn** [comment]
明白了，多谢。
