### ISSUE TITLE
建议在主界面添加“自定义短链接后缀”输入口

### ISSUE THREAD

**Issue by sworduc** [CareyWang/sub-web#134]
建议在主界面添加“自定义短链接后缀”和“密码”输入口，也就是输入密码后可以设置“自定义短链接后缀”

效果如下图

![image](https://github.com/vitaminx/pic/blob/main/github/shortlinks-1.png?raw=true)

懂 vue 的大佬魔改一个也行🙏

**Comment by CareyWang** [comment]
暂无支持计划，担忧隐私问题可自行部署
