### ISSUE TITLE
不兼容最新的node

### ISSUE THREAD

**Issue by sdpong** [CareyWang/sub-web#136]
root@SAFEHOSTNAME:~/sub-web# yarn install
yarn install v1.22.19
warning ../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.13.0"
error Found incompatible module.

**Comment by wsoso** [comment]
有解决吗？

**Comment by CareyWang** [comment]
无支持其他 node 版本计划，目前也没有必要升级
