### ISSUE TITLE
新人求助

### ISSUE THREAD

**Issue by xiaoqi2020** [CareyWang/sub-web#137]
![image](https://github.com/CareyWang/sub-web/assets/50669177/b4811aa9-7d06-4297-99ec-63891811a37a)
左边是自己docker拉取的镜像，右边是别人的网站打开的样子
问：
1、后端地址怎么设置默认的？
2、远程配置跟别人的不一样，我要修改哪里才可以和别人的一样呢？
3、客户端选项里面的也不一样
4、右上角的版本号可以不显示吗？
5、是否可以用php之类的运行起来而不用docker？

我看别人搭建也是同一个镜像呀！

**Comment by CareyWang** [comment]
部署与改造需要掌握一定编程基础和前端知识，建议使用现有服务
