### ISSUE TITLE
ss订阅链接不能运行

### ISSUE THREAD

**Issue by Codesmadness** [CareyWang/sub-web#14]
ss订阅链接转换成clashr链接后不能在openclash上运行

**Comment by BROBIRD** [comment]
这好像和这个项目没有关系吧

**Comment by CareyWang** [comment]
> ss订阅链接转换成clashr链接后不能在openclash上运行

本地检查后，若还有问题，请到 openclash 或 subconverter 相关项目 issue 咨询。

**Comment by lwx-bupt** [comment]
用什么转换的？可能是转换设置问题
