### ISSUE TITLE
env环境变量

### ISSUE THREAD

**Issue by daomengRen** [CareyWang/sub-web#147]
请问env中VUE_APP_SUBCONVERTER_DEFAULT_BACKEND 和 VUE_APP_CONFIG_UPLOAD_API 这两个环境变量指的是后端服务地址吗,  如果是自建subconverter的话,是应该改为 http://ip:port 吗，求大佬解答，谢谢

**Comment by CareyWang** [comment]
修改 `VUE_APP_SUBCONVERTER_DEFAULT_BACKEND` 或网页端直接按提示输入均可

**Comment by daomengRen** [comment]
好的，那这两个环境变量保持默认就行了吧
