### ISSUE TITLE
用NGINX配置，为什么总是提示要打开JAVASCIPT呢？

### ISSUE THREAD

**Issue by jerrell851** [CareyWang/sub-web#15]
请教一下，我的NGINX配置如下，其中DIST是运行 yarn build生成的，所以NODEJS和YARN都是安装没问题的。

    location /web {
      alias /home/subweb/dist;
    }

目前访问 domain.com/web 页面的时候，打开的是空白页面，查看源码提示如下：

  | <!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><link rel=icon href=/favicon.ico><title>sub-web</title><link href=/js/chunk-35c839bb.7bb60c95.js rel=prefetch><link href=/css/app.6a5dab7f.css rel=preload as=style><link href=/css/chunk-vendors.43fc3011.css rel=preload as=style><link href=/js/app.49500d23.js rel=preload as=script><link href=/js/chunk-vendors.f8fb536e.js rel=preload as=script><link href=/css/chunk-vendors.43fc3011.css rel=stylesheet><link href=/css/app.6a5dab7f.css rel=stylesheet></head><body><noscript><strong>We're sorry but sub-web doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id=app></div><script src=/js/chunk-vendors.f8fb536e.js></script><script src=/js/app.49500d23.js></script></body></html>
-- | --

**Comment by CareyWang** [comment]
由于项目架构特性，配置到二级目录需要修改较多配置参数，如 `webpack` 打包输出路径，路由的根路径，各种资源引用修改为相对路径，nginx 配置 `try_files`。有兴趣可以自行研究，Google 搜索关键词『Vue项目编译后部署在非网站根目录』。

**Comment by jerrell851** [comment]
> 由于项目架构特性，配置到二级目录需要修改较多配置参数，如 `webpack` 打包输出路径，路由的根路径，各种资源引用修改为相对路径，nginx 配置 `try_files`。有兴趣可以自行研究，Google 搜索关键词『Vue项目编译后部署在非网站根目录』。

看了相关的资料，也知道的修改的方法。但我没找到网上修改例子中提到的config/index.js文件，请问您这个项目的这个文件是存放在哪个路径下面的？或者您是否可以指出大概需要修改您项目的哪些文件，给个文件列表给我，我慢慢琢磨。

**Comment by CareyWang** [comment]
项目基于 vue-cli 开发，webpack 相关配置位于根目录下 vue.config.js，类似：
```javascript
module.exports = {
  publicPath: '/web/'
}
```

vue-router 相关配置位于 src/router/index.js。

更多配置细节可以参考 [vue-cli 文档](https://cli.vuejs.org/zh/config/#vue-config-js)。
