### ISSUE TITLE
docker部署之后，希望可以记忆后端地址。

### ISSUE THREAD

**Issue by mufengyouyang** [CareyWang/sub-web#158]
每次打开网页都需要重新输入后端地址有些麻烦，要是有记忆功能就好了

**Comment by gongyu** [comment]
Deploy
发布到线上环境，你需要安装依赖，执行以下打包命令，生成的 dist 目录即为发布目录。如需修改默认后端，请修改 src/views/Subconverter.vue 中 defaultBackend 配置项。

yarn build

自己看文档。在Subconverter.vue，搜索127.0.0.1修改成你后端地址。
