### ISSUE TITLE
大部分情况下 https://raw.githubusercontent.com/ 无法访问

### ISSUE THREAD

**Issue by gumutianqi** [CareyWang/sub-web#16]
在 Clash 没有就位是，或者，sub-web，以及 subconverter 部署到普通服务器是，https://raw.githubusercontent.com/ 是无法访问的

建议用到的 ini 配置提供一个 git 切换源，如 gitee.com

**Comment by CareyWang** [comment]
@gumutianqi 目前 ini 存储于阿里云OSS，访问情况良好。

**Comment by gumutianqi** [comment]
不是拼接在 config 参数后面的 Online 的 ini 地址么？

**Comment by CareyWang** [comment]
@gumutianqi 若为本仓库内置的规则，会根据网络状况调整存储服务商，他人提供的远程配置无法保证

**Comment by gumutianqi** [comment]
了解了
