### ISSUE TITLE
vercel 无法部署

### ISSUE THREAD

**Issue by SunRunAway** [CareyWang/sub-web#160]
<html>
<body>

Running build in Washington, D.C., USA (East) – iad1
12:40:02.472 | Cloning github.com/SunRunAway/sub-web (Branch: master, Commit: e06b3ed)
12:40:02.790 | Cloning completed: 318.137ms
12:40:02.841 | Previous build cache not available
12:40:03.043 | Running "vercel build"
12:40:03.519 | Vercel CLI 33.5.3
12:40:04.136 | Installing dependencies...
12:40:04.437 | yarn install v1.22.17
12:40:04.517 | [1/4] Resolving packages...
12:40:05.014 | [2/4] Fetching packages...
12:40:19.147 | error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 \|\| 10 \|\| 12 \|\| 14 \|\| 16 \|\| 17". Got "18.18.2"
12:40:19.159 | error Found incompatible module.
12:40:19.162 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
12:40:19.188 | Error: Command "yarn install" exited with 1
12:40:19.544

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by cyczq11** [comment]
我也是遇到这个问题

**Comment by Godtokoo666** [comment]
请尝试更换node版本或更新dependency配置

**Comment by CareyWang** [comment]
Node.js Version 目前需要 16.x

**Comment by chenweiask** [comment]
Vercel计划在24年6月关闭机遇Node.js 16的部署功能了。6月以后就没部署到Vercel，大家抓紧时间！
