### ISSUE TITLE
从URL解析时会出错

### ISSUE THREAD

**Issue by AAZhe1997** [CareyWang/sub-web#164]
如果在进阶模式下选择“从URL解析”，原链接不包含include内容的话，在生成的链接会自动添加&include=null，导致订阅出错
![image](https://github.com/CareyWang/sub-web/assets/63895332/bc2ab68b-dae1-42ca-8f4e-267373efa427)
![image](https://github.com/CareyWang/sub-web/assets/63895332/7d97dd89-b679-4df9-9d64-f4b828fc9a6c)

**Comment by CareyWang** [comment]
fixed
