### ISSUE TITLE
繁体解析不了

### ISSUE THREAD

**Issue by wang93wei** [CareyWang/sub-web#18]
节点信息是繁体的，现在会提示不包含任何节点信息

![image](https://user-images.githubusercontent.com/6371053/82476570-dee3d580-9b00-11ea-9257-869285372741.png)

其他家可以正常解析订阅地址
![image](https://user-images.githubusercontent.com/6371053/82476749-1783af00-9b01-11ea-82e8-c046453d72eb.png)

**Comment by CareyWang** [comment]
可在 [后端开发群](https://t.me/subconverter_discuss) 中提供订阅咨询开发者

**Comment by JuneZhao** [comment]
@wang93wei  客户端改成clashR 就好了，我刚才试了一下

**Comment by wang93wei** [comment]
> @wang93wei 客户端改成clashR 就好了，我刚才试了一下

后端的问题，，，我之前搞差了-0-

网站没找到联系后端的位置
