### ISSUE TITLE
能有比较详细的使用说明吗？安装完你的前端，还需要装subconverter吗？搭建起来出现网络错误的，不知道如何排查

### ISSUE THREAD

**Issue by gzgaryli** [CareyWang/sub-web#19]

**Comment by CareyWang** [comment]
@gzgaryli 可参考 https://agwa5783.gitbook.io/sub-web/

**Comment by gzgaryli** [comment]
感谢回复，前端，fork了，并根据要求改了const defaultBackend为自己的域名。后端就直接用AGWA的clone。 然后出现错误了。
1. 现在的订阅连接，域名后面小了sub?
2. 我人工加了，就是网络错误。
3. 这就是链接，https://api.gzth.mltarget=clash&url=trojan%3A%2F%2FCwzIG%40gzth.cf%3A443&insert=false

如果有时间，帮我看一看啦

谢谢

**Comment by CareyWang** [comment]
@gzgaryli 只需要替换域名部分。后续路由路径不要修改

**Comment by gzgaryli** [comment]
通过这个链接 https://raffz.com/posts/deploy_subconverter/，然后加你的说明，就成功了，谢谢

非常好用
