### ISSUE TITLE
关于更多选项中的 排序节点

### ISSUE THREAD

**Issue by zack66** [CareyWang/sub-web#2]
![image](https://user-images.githubusercontent.com/16634459/75059442-ebfc2300-5517-11ea-831f-5b53222c6de1.png)

选中或未选中该选项 生成的订阅链接都无变化

![image](https://user-images.githubusercontent.com/16634459/75059667-6c228880-5518-11ea-8ca7-7484bf9ff3b7.png)

查看代码发现生成订阅时少了 &sort= 参数

**Comment by CareyWang** [comment]
@zack66 Fixed, thanks!
