### ISSUE TITLE
Request Feature: Clash to V2RAY subscription.

### ISSUE THREAD

**Issue by m4niacjp** [CareyWang/sub-web#22]
Is it possible to get from Clash to a V2RAY, BASE64, VMESS subscription to be used in V2rayNG and similar?

**Comment by CareyWang** [comment]
@m4niacjp Now you can select v2ray in the client type.

**Comment by m4niacjp** [comment]
On the page https://sub.dler.io/ i can't see it yet?

**Comment by CareyWang** [comment]
https://sub.dler.io/ is maintained by a third party. You can use my service to get the lastest features: https://sub-web.wcc.best

**Comment by m4niacjp** [comment]
Thanks!
