### ISSUE TITLE
这个变更的兼容性能适配吗？

### ISSUE THREAD

**Issue by commis** [CareyWang/sub-web#23]
上游 Clash 核心已移除前向兼容代码

包括但不限于

- 不再解析 "Proxy" "Proxy Group" "Rule" 字段 而 使用 "proxies" "proxy-groups" "rules"
- 不再解析 "rule-provider" 而使用 "rule-providers"
- 不再解析 Shadowsocks 协议的 "obfs", "obfs-host" 而 使用 "plugin" "plugin-opts"
- 不再解析 "FINAL" "SOURCE-IP-CIDR" 而 使用 "MATCH" "SRC-IP-CIDR"

Clash for Android 会为该变更保留 2个月 的前向兼容 各位 用户 及 提供商 尽快适配新的配置文件规范

参见 commit
 - 2781090
 - e57a13e

**Comment by CareyWang** [comment]
@commis 适配需配合最近版本的后端使用，前端在若干个版本前已支持Clash New Field选项。

**Comment by commis** [comment]
> @commis 适配需配合最近版本的后端使用，前端在若干个版本前已支持Clash New Field选项。

我不要用的是clash的客户端clash for android，clash的更新如下，不知道这里是否可以做适配。
https://github.com/Dreamacro/clash/wiki/Breaking-Changes-in-1.0.0

**Comment by CareyWang** [comment]
@commis 仓库介绍中提供的 api 服务在若干个版本前已经兼容本次变更。第三方提供的服务没有更进前端近期更新，也不了解其后端版本，无法保证适配情况，如需使用请自行联系服务提供方。
