### ISSUE TITLE
上传配置文件限制

### ISSUE THREAD

**Issue by QuteSaltyFish** [CareyWang/sub-web#25]
你好。。我想上传一个自己的配置文件，基于ACL4SSR full修改的，但是好像超出3000个的限制了。。。难受了

**Comment by CareyWang** [comment]
@QuteSaltyFish 有求必应系列，已提高上限至5000，仓库中示例页已发布生效。

**Comment by Curious-r** [comment]
@CareyWang 佬，5000也不太够用了，能再大点吗
