### ISSUE TITLE
执行   docker-compose up -d  报错

### ISSUE THREAD

**Issue by mengyalei** [CareyWang/sub-web#26]
root@debian:~/sub-web# docker-compose up -d
报错信息如下：
ERROR: yaml.scanner.ScannerError: while scanning a plain scalar
  in "./docker-compose.yaml", line 19, column 73
found unexpected ':'
  in "./docker-compose.yaml", line 19, column 85

请问下这个怎么解决呢？感谢！

**Comment by CareyWang** [comment]
@mengyalei 升级 docker docker-compose 到最新版本
