### ISSUE TITLE
web中直接上传配置不能使用

### ISSUE THREAD

**Issue by QuteSaltyFish** [CareyWang/sub-web#27]
我上传了如下的配置（一个subconverter中的预设配置），但是出来的结果并不是按照它所写的这样，请问是我这个配置文件用的不对还是存在bug啊
<img width="966" alt="Screen Shot 2020-07-14 at 17 52 51" src="https://user-images.githubusercontent.com/41997780/87411834-d983a280-c5fa-11ea-94e5-358da29a5edb.png">

**Comment by CareyWang** [comment]
@QuteSaltyFish 前天由于机器到期，更换了一台备用机，存在一些奇奇怪怪的原因导致外部配置没用读取成功。目前已更换新机器，可以重新尝试一下。
