### ISSUE TITLE
docker容器内找不到src目录

### ISSUE THREAD

**Issue by DockerYumeko** [CareyWang/sub-web#31]
如标题，拉取这个镜像之后，找不到src目录 但是还正常可以运行，请问下，docker内这个目录在哪

**Comment by CareyWang** [comment]
```
/usr/share/nginx/html
```

**Comment by DockerYumeko** [comment]
没有找到这个
/usr/share/nginx/html # ls
50x.html     _redirects   css          favicon.ico  fonts        index.html   js
该目录下只有这几个 文件/文件夹

**Comment by CareyWang** [comment]
@DockerYumeko 打包之后的文件，就是这些

**Comment by DockerYumeko** [comment]
那在docker容器里 修改不了Subconverter.vue文件吗?

**Comment by CareyWang** [comment]
@DockerYumeko 如果需要使用docker，并且想修改页面文件，请自行了解docker镜像构建相关流程以及前端打包基础概念，修改完成后本地构建镜像并运行服务。

**Comment by DockerYumeko** [comment]
好的，谢谢
