### ISSUE TITLE
include_remarks from .ini file

### ISSUE THREAD

**Issue by m4niacjp** [CareyWang/sub-web#35]
If i use option inlcude remarks from website it's working perfectly, but if i use a .ini file that has the following line:

`include_remarks=(香港)
`

Still i can see all server, is not filtering.

This line is ok!

`exclude_remarks=(abc)
`

**Comment by CareyWang** [comment]
This is a backend issue, you can submit an issue in the [backend project](https://github.com/tindy2013/subconverter/issues) or ask in the [telegram group](https://t.me/subconverter_discuss).
