### ISSUE TITLE
魅影极速的配置无法导入quantumult x

### ISSUE THREAD

**Issue by FanyangMengDev** [CareyWang/sub-web#4]
您的网站和我的网站都试了一遍发现都不可以，可否试一下？
总是显示语法错误，很奇怪

**Comment by CareyWang** [comment]
@FanyangMengDev 勾选NodeList

**Comment by FanyangMengDev** [comment]
哇这回复速度我爱了大佬😂感谢感谢

**Comment by FanyangMengDev** [comment]
还是不行，魅影极速的订阅链接，maying配置文件，勾选nodelist，emoji之后，quantumult x里面配置文件下载还是出错，我看输出最前面竟然是shadowsocks，而不是ssr很奇怪，想问下大佬这是为什么呢

**Comment by CareyWang** [comment]
@FanyangMengDev 检查下客户端是否选择了QuantumultX，是否勾选了NodeList，是否在Quanx中节点的引用处添加的订阅

**Comment by FanyangMengDev** [comment]
大佬我试了一下节点是可以添加成功的，但是目前只能在quanx里添加节点，然而是无法直接通过配置url导入各种规则对吗？

**Comment by CareyWang** [comment]
@FanyangMengDev 是的，这个问题已经反馈给后端开发者了，后续可能解决。

**Comment by FanyangMengDev** [comment]
好的好的，真好加了tindy的tg，持续关注一波

**Comment by CareyWang** [comment]
问题已定位，QuanX 中策略组名不能为『Proxy』，修改即可。
