### ISSUE TITLE
基础模式 页面 缓存问题

### ISSUE THREAD

**Issue by ccgakki** [CareyWang/sub-web#44]
我想问一下  每次基础模式生成订阅之后，刷新浏览器之后 ，原订阅链接仍然在页面上，请问怎么改变，刷新或短时间清除之前填的链接。
是修改env 的vue ttl 时间吗？更改之后不起作用。

**Comment by CareyWang** [comment]
@ccgakki 手动删除输入框的链接，再移出光标关闭页面。默认保存上一次的链接到浏览器本地

**Comment by ccgakki** [comment]
谢谢大佬。我就是想做个和大佬一样的转换链接https://subcon.dlj.tf，刷新之后订阅链接会变成空白，方便填下一个。我自己搭的做不到😅

**Comment by ccgakki** [comment]
是版本的问题么...我搭的0.6.4版本

**Comment by CareyWang** [comment]
@ccgakki 这个是后端作者自己做的前端，跟本项目没有关系。

**Comment by BROBIRD** [comment]
@ccgakki  你是用的Firefox吗

**Comment by ccgakki** [comment]
Safari

**Comment by limr95** [comment]
把@blur和下面的定义savesub删了就行
