### ISSUE TITLE
重构镜像无法成功，提示FROM node:lts-alpine AS dependencies

### ISSUE THREAD

**Issue by iJayscn** [CareyWang/sub-web#47]
Sending build context to Docker daemon   155 MB
Step 1/12 : FROM node:lts-alpine AS dependencies
Error parsing reference: "node:lts-alpine AS dependencies" is not a valid repository/tag: invalid reference format

请问如何解决？

**Comment by CareyWang** [comment]
@iJayscn 安装最新版本 docker

**Comment by iJayscn** [comment]
更新后已解决！谢谢
