### ISSUE TITLE
如何更改基础模式 的默认策略组？

### ISSUE THREAD

**Issue by ccgakki** [CareyWang/sub-web#51]
你好，比如 我想用 
label: "Basic(仅GEOIP CN + Final)",
                value:
                  "https://subconverter.oss-ap-southeast-1.aliyuncs.com/Rules/RemoteConfig/special/basic.ini"
进阶策略的这个，添加在基础模式的默认规则，应该怎么做？

**Comment by MFYDev** [comment]
issue不是提这种问题的地方，但凡会一点点代码也不至于问这种问题。

https://github.com/CareyWang/sub-web/blob/46c43c69b5e6c7d16e3437a37568c5452a3dae62/src/views/Subconverter.vue

**Comment by CareyWang** [comment]
@ccgakki 设置 form.remoteConfig 为你需要的值即可。
