### ISSUE TITLE
docker-compose.yaml 里的myurles-redis是不是缺了个引号

### ISSUE THREAD

**Issue by xufzh** [CareyWang/sub-web#6]
运行docker-compose up -d报错，加了引号没问题了

**Comment by CareyWang** [comment]
@xufzh docker-compose version 1.25.4, build 8d51620a 没有问题，可以升级下 docker-compose 版本。

**Comment by xufzh** [comment]
> @xufzh docker-compose version 1.25.4, build 8d51620a 没有问题，可以升级下 docker-compose 版本。

好的，我来试试，谢谢🙏
