### ISSUE TITLE
如何配置短链接

### ISSUE THREAD

**Issue by lycor1s** [CareyWang/sub-web#7]
域名已解析，配置了`MYURLS_DOMAIN=api.example.com`，然后用nginx反代了sub-web ，生成短链接的地址还是https://suo.yt开头的地址

**Comment by CareyWang** [comment]
@lycor1s 如果要使用MyUrls前端生成短链的话，目前不支持根据参数定义短链后端，需要单独部署项目并参考README修改对应后端域名，不使用短链前端的话不影响。建议深度玩法参考 https://agwa5783.gitbook.io/sub-web/ 部署。

**Comment by lycor1s** [comment]
OK成功了，感谢
