### ISSUE TITLE
Docker安装后如何修改Subconverter.vue文件？

### ISSUE THREAD

**Issue by yggcwx** [CareyWang/sub-web#84]
我先后尝试过两次部署sub-web：第一次是通过执行`git clone https://github.com/CareyWang/sub-web.git`命令的方式，第二次是通过`docker run -d -p 58080:80 --restart always --name subweb careywong/subweb:latest`的方式。
　　在第一种方式中，我很容易的找到了Subconverter.vue文件（/root/sub-web/src/views/Subconverter.vue），并修改了默认后端地址。但因这种方式安装的程序bug较多，启动缓慢，我随后只得通过docker方式重新部署。部署后，不论是进入容器后查找Subconverter.vue文件，还是查找sub-web/src/views/目录，均告失败。
　　请高手指点，在docker中，我该如何找到并修改Subconverter.vue文件？
　　谢谢！

**Comment by CareyWang** [comment]
@yggcwx 先修改文件，再执行 docker build。docker内app具体路径，可在 Dockerfile 找到

**Comment by yggcwx** [comment]
> Dockerfile

可是，我又该如何找到并查看Dockerfile文件呢？纯小白，抱歉啊

**Comment by CareyWang** [comment]
@yggcwx 仓库根目录下

**Comment by yggcwx** [comment]
衷心感谢亲自指点！

**Comment by CareyWang** [comment]
理论无需关心docker内文件，修改后再执行build即可生效
```
docker build -t subweb-local:latest .
docker run -d -p 58080:80 --restart always --name subweb subweb-local:latest
```

**Comment by yggcwx** [comment]
多谢多谢！已收藏！
