### ISSUE TITLE
前端没有跳过证书验证的选项

### ISSUE THREAD

**Issue by Karmylr** [CareyWang/sub-web#86]
如题

**Comment by Karmylr** [comment]
![image](https://user-images.githubusercontent.com/69903376/149059103-f915f194-bfd6-47ff-9e51-3cb088de97ef.png)

**Comment by CareyWang** [comment]
Done

**Comment by Karmylr** [comment]
多谢大佬!

**Comment by caliban511** [comment]
> Done

大佬，求更新docker版，，，docker版上次更新还在2021年啊，，，

**Comment by CareyWang** [comment]
@caliban511 已更新

**Comment by caliban511** [comment]
> @caliban511 已更新

感谢大佬。👍👍👍
