### ISSUE TITLE
这前端还带追踪的吗

### ISSUE THREAD

**Issue by Karmylr** [CareyWang/sub-web#89]
![image](https://user-images.githubusercontent.com/69903376/150059282-d586a833-7efd-49be-81c7-a980a34fc41f.png)

**Comment by CareyWang** [comment]
基于 [umami](https://umami.is/docs/about ) 的匿名访问统计，不喜可自建自行删除

**Comment by fatFire** [comment]
> 基于 [umami](https://umami.is/docs/about) 的匿名访问统计，不喜可自建自行删除

代码在哪里删除？

**Comment by oshino29** [comment]
> > 基于 [umami](https://umami.is/docs/about) 的匿名访问统计，不喜可自建自行删除
> 
> 代码在哪里删除？

fork 项目之后删除 `public/index.html` 里的这一行：
```html
    <script async defer data-website-id="b1873884-fbbf-4397-9982-5c83d381d94c" src="https://analytics.ytt.yt/umami.js"></script>
```

然后把 fork 之后的项目下载到本地， `docker build . -t subweb:latest`
