### ISSUE TITLE
可否在生产环境中使用CDN引入资源？

### ISSUE THREAD

**Issue by BROBIRD** [CareyWang/sub-web#9]
尝试使用`webpack-cdn-plugin`进行引入但是好像效果不明显（似乎是失败了），想请教一下是否可以通过CDN优化以及正确的引入姿势是什么？谢谢！

**Comment by CareyWang** [comment]
有什么方面或者扩展要引入CDN优化的？

**Comment by BROBIRD** [comment]
> 
> 
> 有什么方面或者扩展要引入CDN优化的？

Vue, Vue-router, Axios这些应该都可以引入CDN吧，部署在按流量计费的机器和CDN上还是想能尽量减小一点开销

**Comment by CareyWang** [comment]
@BROBIRD 目前项目只有一个页面，文件总计不超过300KB，CDN对这种低流量的小网站优势很小，反而会有可能因为用户到一些CDN服务器（如CF）速度不佳影响页面加载速度。
项目使用了babel-plugin实现了模块化按需加载，每个页面只会加载用到的组件，webpack打包与gzip压缩后，流量开销已经不是重点了。如果确实有流量方面的考虑，欢迎使用 netlify 或者 now.sh 此类托管前端服务。

**Comment by BROBIRD** [comment]
> 
> 
> @BROBIRD 目前项目只有一个页面，文件总计不超过300KB，CDN对这种低流量的小网站优势很小，反而会有可能因为用户到一些CDN服务器（如CF）速度不佳影响页面加载速度。
> 项目使用了babel-plugin实现了模块化按需加载，每个页面只会加载用到的组件，webpack打包与gzip压缩后，流量开销已经不是重点了。如果确实有流量方面的考虑，欢迎使用 netlify 或者 now.sh 此类托管前端服务。

我看了下 生产环境编译出的文件大概是1M左右，gzip压缩后是400K左右，确实不大，我用的cdn访问速度很好，所以主要关注流量方面的问题。谢谢解答
