### ISSUE TITLE
请问能自定义 后端地址选框 的名称吗？

### ISSUE THREAD

**Issue by exlulu** [CareyWang/sub-web#99]
backendOptions: [{ value: "http://127.0.0.1:25500/sub?" }],后端地址选框就会显示 http://127.0.0.1:25500/sub?
我试过添加label参数，backendOptions: [{ label: "本地",value: "http://127.0.0.1:25500/sub?" }],但是没效果
能否自定义后端地址选框显示 本地，实际地址是http://127.0.0.1:25500/sub? 这样的效果？

**Comment by CareyWang** [comment]
@exlulu el-autocomplete 组件不支持，可自行修改至 Select 选择器

**Comment by exlulu** [comment]
> @exlulu el-autocomplete 组件不支持，可自行修改至 [Select 选择器](https://element.eleme.cn/#/zh-CN/component/select)

明白，谢谢
